// Generated by version 0.1a
int* methods[];
size_t methodsSize[];
size_t localsCount[];
char** strings[];
float* floats[];
double* doubles[];
int* ints[];
long* longs[];
runtime_func* methodRefs[];

void load()
{

	// Method System.Void TestProjectConsole.Program::Main(System.String[])
	static int methods0[] = {32,0,10,114,0,6,-1,0,-1,1,42};
	methods[0] = methods0;
	methodsSize[0] = 11;
	static char* strings0[] = {"t "};
	strings[0] = strings0;
	static int ints0[] = {240};
	ints[0] = ints0;
	static runtime_func methodRefs0[] = {System_String_Concat2,System_Console_WriteLine1};
	methodRefs[0] = methodRefs0;
	localsCount[0] = 1;
}

int* methods[1];
size_t methodsSize[1];
size_t localsCount[1];
char** strings[1];
float* floats[1];
double* doubles[1];
int* ints[1];
long* longs[1];
runtime_func* methodRefs[1];
