// Generated by version 0.1a
#include <output.h>
void load()
{

	// Method System.Void TestProjectConsole.Program::test(System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32)
	static int methods1[] = {114,0,2,114,1,-1,0,0,-1,1,0,114,2,3,-1,2,0,-1,3,0,114,3,4,5,88,14,4,88,14,5,88,-1,4,0,-1,5,0,42};
	methods[1] = methods1;
	methodsSize[1] = 38;
	static char* strings1[] = {"-> num ",".","-> num2 ","-> a+b+c+d "};
	strings[1] = strings1;
	static runtime_func methodRefs1[] = {System_String_Concat3,System_Console_WriteLine1,System_String_Concat2,System_Console_WriteLine1,System_String_Concat2,System_Console_WriteLine1};
	methodRefs[1] = methodRefs1;
	localsCount[1] = 0;
	// Method System.Int32 TestProjectConsole.Program::returnvaluetest(System.Int32)
	static int methods2[] = {2,2,90,2,30,88,90,31,0,90,10,43,13,6,42};
	methods[2] = methods2;
	methodsSize[2] = 15;
	static int ints2[] = {12};
	ints[2] = ints2;
	localsCount[2] = 1;
	// Method System.Void TestProjectConsole.Program::Main(System.String[])
	static int methods0[] = {23,10,22,11,43,39,6,6,29,97,23,24,25,26,40,1,6,114,0,7,40,2,1,-1,0,0,-1,1,0,6,24,90,10,7,12,8,23,88,11,7,26,-508,13,9,45,6,42};
	methods[0] = methods0;
	methodsSize[0] = 47;
	static char* strings0[] = {"returnvaluetest: "};
	strings[0] = strings0;
	static runtime_func methodRefs0[] = {System_String_Concat2,System_Console_WriteLine1};
	methodRefs[0] = methodRefs0;
	localsCount[0] = 4;
}

int* methods[3];
size_t methodsSize[3];
size_t localsCount[3];
char** strings[3];
float* floats[3];
double* doubles[3];
int* ints[3];
long* longs[3];
runtime_func* methodRefs[3];
